languageCode = "id"
title = "PUSTAKA SAGA"
theme = "hugo-initio"
pluralizelisttitles = false

[params]
    name = "Pustaka Saga"
    description = "pustaka saga jawadwipa"
    email = "pustaka.saga23@gmail.com"
    phone = "085655396657"
    address = "Jl. Kedinding Lor, gg. Delima 4A Surabaya"
    year = 2023
    avatar = "/images/pustaka-saga.png"
    avatarclass = "saga"
    background = ""
    banner = ""
    favicon = "/images/pustakasagaicon.jpg"
    DateForm = "July 17, 2023"
    author = "Pustaka Saga"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "terbitan"
    url = "/terbitan/"
    weight = 2
[[menu.main]]
    name = "jurnal saga"
    url = "/jurnal-saga/"
    weight = 10
#[[menu.main]]
    #name = "blog"
    #url = "/blog/"
    #weight = 5

#[params.disqus]
    #site = "hugo-initio-site.disqus.com"

#[params.sharethis]
    #property = "123456789012345678901234"
    #custom = true

#[params.google.analytics]
    #trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/pustaka.saga"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/pustakasaga"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/pustakasaga"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
